### ISSUE TITLE
Discussion for first version

### ISSUE THREAD

**Issue by dreamflasher** [IntuitionMachines/AzureMLTools#1]
We want to have shared code for loading data. Thoughts that I/we have:
All datasets should be at one location, eg. Azure Blob storage
Loader should support multithreading
A first idea for speedup is to 1) downscale images to 400*400px, 2) pickle in compressed format
A while ago I looked into what’s the most efficient compression algorithm, there's this benchmark: 
https://github.com/inikep/lzbench/blob/master/lzbench171_sorted.md – unfortunately, it's outdated. 
Good algorithms according to this are: lzsse8 (no python bindings), lizard (no python bindings), LZ4 (although lzsee8 is significantly faster, LZ4 is the best one that has python bindings: https://github.com/python-lz4/python-lz4/) – so I suggest LZ4.

**Comment by harpone** [comment]
FYI there's now a numpy version of imagenet training set in the blob storage here: https://eastcoastdatasets2.blob.core.windows.net/imagenet2/train_numpy/

going to run some tests ASAP

**Comment by dreamflasher** [comment]
A while ago I benchmarked the following: This was from reading a 10 million lines CSV file, (20 columns I think), I compared a bunch of different things, but the gist is: "pandas pickled gzip" has the smalles file size and is the fastest.
hdf5 itertuples is 6 times bigger and 5 times slower
msgpack streamed gzip is 5 times bigger and 80 times slower
same for marshal gzip
but this was for text only, so I don't know how the performance is for JPGs
so I definitely would give images in pandas dataframes gzipped (and even better lz4) a try

**Comment by tebishop** [comment]
possibly no longer relevant with caching jpgs from local SSD, but may want to revisit?
worth looking into persistent SSDs.
