### ISSUE TITLE
autoresume does not use correct commit when autoresuming

### ISSUE THREAD

**Issue by harpone** [IntuitionMachines/AzureMLTools#5]
So changes in the code can break training... maybe fix so that launcher will checkout the correct commit before resuming?

**Comment by harpone** [comment]
Actually the autoresume thing is dangerous also in other ways: if e.g. you edit the launch script and autoresume happens to resubmit a job then, it will e.g. upload the new and _wrong_ launch script to the checkpoints :P this needs some more thought

**Comment by dreamflasher** [comment]
Maybe remove it for now?

**Comment by harpone** [comment]
I wrote a quick fix to check if the launch script is already present in the checkpoint blob storage, and not to upload it if it is... so hacky solution, but seems to work... still the autoresume thing is not a very good solution in the long term. I have a bit of a beef with the way Azure ML also handles the job submission by packaging the entire project and uploading to AML... why can't everything just be cloned from git? We had that at Curious AI and it was working really well (well, I wasn't involved in the backend stuff so don't know what happened behind the scenes there...)

**Comment by harpone** [comment]
and of course you can set autoresume=False
